namespace: argocd
resources:
- argocd.yaml
- certmanager.yaml
- drzzlio.yaml
- jspolicy.yaml
- gptpolicy.yaml
- httpbin.yaml
- k0smotron.yaml
- yoke.yaml

patches:
- path: ğŸ°.ğŸªš.yaml
  target:
    group: argoproj.io
    kind: Application
